<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <PackageId>TheWheel.OpenXml.WebApi</PackageId>
    <Authors>Nicolas</Authors>
    <Company>Nicolas</Company>
    <PackageProjectUrl>https://github.com/npenin/thewheel-dotnet</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Description>Adds a new web api formatter to handle rendering in xslx</Description>
    <Copyright>Copyright 2022</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Condition="'$(TargetFramework)' != 'net48'" Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheWheel.OpenXml\TheWheel.OpenXml.csproj" />
    <ProjectReference Include="..\TheWheel.Lambda\TheWheel.Lambda.csproj" />
  </ItemGroup>

  <ItemGroup></ItemGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>