<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
    <PackageId>TheWheel.Dto</PackageId>
    <Authors>Nicolas</Authors>
    <Company>Nicolas</Company>
    <PackageProjectUrl>https://github.com/npenin/thewheel-dotnet</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Description>Contains helper for integration with client side table view</Description>
    <Copyright>Copyright 2022</Copyright>
  </PropertyGroup>

  <ItemGroup></ItemGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>