name: .NET

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"
      - name: Restore dependencies
        run: dotnet restore TheWheel.sln
      - name: Build
        run: dotnet build --no-restore  TheWheel.sln
      - name: retrieve test file
        run: wget https://cve.mitre.org/data/downloads/allitems-cvrf-year-2020.xml
      - name: debug
        run: ls -l
      - name: Test
        run: dotnet test --no-build --verbosity normal TheWheel.sln
      - name: Git Version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: main
        id: version
      - name: Pack nuspec packages
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          nuget pack TheWheel.Lambda/Package.nuspec -Version ${{ steps.version.outputs.version }} -Properties Configuration=Release -Symbols
          nuget pack TheWheel.Domain/Package.nuspec -Version ${{ steps.version.outputs.version }} -Properties Configuration=Release -Symbols
          nuget pack TheWheel.WebApi/Package.nuspec -Version ${{ steps.version.outputs.version }} -Properties Configuration=Release -Symbols
          nuget pack TheWheel.Services/Package.nuspec -Version ${{ steps.version.outputs.version }} -Properties Configuration=Release -Symbols
          nuget pack TheWheel.Dto/Package.nuspec -Version ${{ steps.version.outputs.version }} -Properties Configuration=Release -Symbols
          nuget pack TheWheel.OpenXml/Package.nuspec -Version ${{ steps.version.outputs.version }} -Properties Configuration=Release -Symbols
          nuget pack TheWheel.OpenXml.WebApi/Package.nuspec -Version ${{ steps.version.outputs.version }} -Properties Configuration=Release -Symbols
          nuget pack TheWheel.ServiceBus/Package.nuspec -Version ${{ steps.version.outputs.version }} -Properties Configuration=Release -Symbols
      - name: Pack dotnet projects
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet pack TheWheel.ETL.Contracts -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.ControlFlow -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.Providers -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.Provider.Ldap -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.Provider.Mail -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.Snow -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.Jira -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.Fluent -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.DacPac -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.CyberArk -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.Azure -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.ETL.Parlot -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
          dotnet pack TheWheel.Mail -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --include-symbols --include-source
      - name: Upload packages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: |
            *.nupkg
            *.snupkg
      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
