name: .NET

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NuGetDirectory: ${{ github.workspace}}/nuget
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"
      - name: install mono
        run: |
          sudo apt install ca-certificates gnupg
          sudo gpg --homedir /tmp --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          sudo chmod +r /usr/share/keyrings/mono-official-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update
          sudo apt install mono-devel libldap2
          sudo ln -sf /usr/lib/x86_64-linux-gnu/libldap.so.2 /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0
          sudo ln -sf /usr/lib/x86_64-linux-gnu/liblber.so.2 /usr/lib/x86_64-linux-gnu/liblber-2.5.so.0
      - name: Restore dependencies
        run: dotnet restore TheWheel.sln
      - name: Build
        run: dotnet build --no-restore TheWheel.sln
      - name: retrieve test file
        run: wget https://cve.mitre.org/data/downloads/allitems-cvrf-year-2020.xml
      - name: Test
        run: dotnet test --no-build --framework net8.0 --verbosity normal TheWheel.sln
        # - name: Git Version
        #   id: version
        #   uses: codacy/git-version@2.8.7
        #   with:
        #     release-branch: main
      - name: offset version
        id: version
        run: |
          echo "value=$((211 + $GITHUB_RUN_NUMBER))" >> $GITHUB_OUTPUT
      - name: Pack dotnet projects
        run: |
          dotnet pack TheWheel.Lambda -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.Domain -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.WebApi -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.Services -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.Dto -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.OpenXml -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.OpenXml.WebApi -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ServiceBus -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.Contracts -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.ControlFlow -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.Providers -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.Provider.Ldap -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.Provider.Mail -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.Snow -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.Jira -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.Fluent -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.DacPac -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.CyberArk -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.ETL.Azure -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          # dotnet pack TheWheel.ETL.Parlot -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
          dotnet pack TheWheel.Mail -p:PackageVersion=1.${{ steps.version.outputs.value }}.0 --configuration Release --include-symbols --include-source --output ${{ env.NuGetDirectory }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: |
            ${{ env.NuGetDirectory }}/*.nupkg
  deploy:
    name: Deploy NuGet
    environment: nuget
    runs-on: ubuntu-24.04
    # A ready artifact is required before publishing
    # The job waits for the build job to complete
    needs: build
    # This jobs runs if build succeeds
    if: success() && github.ref=='refs/heads/main'
    # Save path to the NuGet directory in the environment variable
    env:
      NuGetDirectory: ${{ github.workspace}}/nuget
    steps:
      # Download the contents of the repository
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
      # Publish the NuGet package using the dotnet utility
      - name: Publish NuGet package
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
